"""Regenerate the two November case-study PNGs at 150 dpi into docs/observable/src/images/.

All plots compare the optimiser against the **deadband thermostat** (the reference
controller cited in the case study), not the LP-baseline. The two-year plot is
produced separately by case_study/baseline_compare_historical_Mar23_Mar25.py, which
runs the chunked monthly solve and writes the matching results file.
"""
import json
from pathlib import Path

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from strom.optimization_utils import House
from strom.plot_utils import plot_combined_cases
from strom.data_utils import remove_temperature_spikes
from case_study.results_utils import solve_or_load_case

DPI = 150
OUT = Path("docs/observable/src/images")
OUT.mkdir(parents=True, exist_ok=True)

with open("config/house_config.json") as f:
    house_cfg = json.load(f)

nov_df = pd.read_csv(
    "data/Temp_Price_Barcelona_Nov.csv",
    index_col="Timestamp", parse_dates=["Timestamp"],
)
nov_df["ExteriorTemperature"] = remove_temperature_spikes(nov_df["ExteriorTemperature"])

# ── 1. Two-day view: 24-25 November ──────────────────────────────────────────
print("=== Plot 1: 24-25 Nov (optimal vs thermostat) ===")
day_df = nov_df[(nov_df.index >= "2024-11-24") & (nov_df.index < "2024-11-26")]
house = House(**house_cfg, freq="5min")
opt_day, _base_day, therm_day = solve_or_load_case(day_df, house, "data/chunks_25thNov")
fig = plot_combined_cases(opt_day, therm_day, compare_label="Thermostat", smooth_min=60)
dest = OUT / "compare_costs_temps_Barcelona_25th_Nov.png"
fig.savefig(dest, dpi=DPI, bbox_inches="tight")
plt.close(fig)
print(f"  Saved {dest}")

# ── 2. November second-half view ─────────────────────────────────────────────
print("=== Plot 2: Nov 15-30 (optimal vs thermostat) ===")
half = len(nov_df) // 2
nov_half_df = nov_df.iloc[half:]
house = House(**house_cfg, freq="5min")
opt_nov, _base_nov, therm_nov = solve_or_load_case(nov_half_df, house, "data/chunks_Nov")
fig = plot_combined_cases(opt_nov, therm_nov, compare_label="Thermostat", smooth_min=60)
dest = OUT / "compare_costs_temps_Barcelona_Nov.png"
fig.savefig(dest, dpi=DPI, bbox_inches="tight")
plt.close(fig)
print(f"  Saved {dest}")

print("Done. (Two-year plot is generated by baseline_compare_historical_Mar23_Mar25.py)")
